### ISSUE TITLE
[BUG]: 10.0 LUA errors.

### ISSUE THREAD

**Issue by Nillx** [HizurosWoWAddOns/Broker_Everything#16] opened 2022-10-28 15:50 UTC
### WoW client

WoW Retail

### What happened?

Hello, are you planning to update this for 10.0? 9.2.7 version cause a lot of errors but its halfway working.

### Lua Error Message?

```lua
1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:135 Unrecognized XML attribute: relativeKey

1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:135 Unrecognized XML attribute: point

1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:135 Unrecognized XML: Anchor

1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:134 Unrecognized XML: Anchors

1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:133 Unrecognized XML attribute: y

1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:133 Unrecognized XML attribute: x

1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:133 Unrecognized XML: Size

1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:132 Unrecognized XML attribute: inherits

1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:132 Unrecognized XML attribute: parentKey

1x Interface/AddOns/Broker_Everything/Broker_Everything.xml:132 Unrecognized XML: Checkbox
```

**Comment by rodalpho** [comment] 2022-10-28 16:00
Yes please. The addon actually seems to largely function, my modules show in my LDB display and all, but there are dozens of errors upon login.

**Comment by rodalpho** [comment] 2022-10-28 16:35
I went through and corrected every error I saw by commenting out code blocks. Steps:
1) Install the latest release version
2) Download a ZIP of the live code from github
3) Copy all the github files over the release files
4) Replace the Broker_Everything.xml file
5) ...
6) profit

XML file: https://controlc.com/21265af3

**Comment by Nillx** [comment] 2022-10-28 17:39
Ok doing that fixed the errors thanks. Noticing an issue with the bag module tho, it thinks my inventory is a 20 slot bag and i have 5 free slots while thats not true.

**Comment by 4C51** [comment] 2022-10-28 22:05
This is a duplicate of #13

**Comment by Spiderkeg** [comment] 2022-10-30 05:25
> I went through and corrected every error I saw by commenting out code blocks. Steps:
> 
> 1. Install the latest release version
> 2. Download a ZIP of the live code from github
> 3. Copy all the github files over the release files
> 4. Replace the Broker_Everything.xml file
> 5. ...
> 6. profit
> 
> XML file: https://controlc.com/21265af3

Good job on fixing a lot of these errors.  I'm still seeing an error with the volume module, something involving the CVar not being a function.  I'm also seeing a lot of addon tab text and module text being surrounded with < > and no idea why.

**Comment by rodalpho** [comment] 2022-10-30 12:19
Yes, it breaks all the localization stuff so you only see variable names now. The addon needs a proper fix, not my amateurish attempt.

**Comment by Spiderkeg** [comment] 2022-10-30 14:51
> Yes, it breaks all the localization stuff so you only see variable names now. Perfectly usable if you read English, but not pretty. The addon needs a proper fix, not my amateurish attempt.

Gotcha.  Thanks for the reply and clarification.

**Comment by JazBlade** [comment] 2022-10-30 18:20
> Yes, it breaks all the localization stuff so you only see variable names now. Perfectly usable if you read English, but not pretty. The addon needs a proper fix, not my amateurish attempt.



> Ok doing that fixed the errors thanks. Noticing an issue with the bag module tho, it thinks my inventory is a 20 slot bag and i have 5 free slots while thats not true.

I'm seeing that too. It's as if its only counting the default bag slot and not any of the slots you put your own bags into

**Comment by hizuro** [comment] 2022-10-31 22:22
Thank you for reporting. Please try version 4.4.1.

**Comment by Nillx** [comment] 2022-10-31 22:56
Installed 4.4.1 and im getting the same errors. Bag plugin is no longer showing like 3-4 free spots but its still incorrect.

**Comment by Nillx** [comment] 2022-10-31 23:48
4.4.2 fixed the issue, im not getting any errors. Bag issue is still present, it constantly change when i move items around my inventory Example here: https://imgur.com/a/rEfkuC2

**Closed** 2023-01-17 02:14 UTC
Labels: bug
